language: java

jdk:
    - openjdk7
    - openjdk6
    - oraclejdk7

notifications:
  email: false

# blacklist upstream build since they will not have a TravisCI config
branches:
  except:
    - upstream

